<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Enhancements">
    <meta name="author" content="Winson Tan">
    <link rel="stylesheet" href="styles/style.css">
    <title>Enhancements</title>
</head>
<body>
<nav>
    <a href="index.php">Home</a>
    <a href="about.php">About Us</a>
    <a href="jobs.php">Job Details</a>
    <a href="apply.php">Apply Job</a>
    <a class="active" href="enhancements.php">Enhancements</a>
</nav>
